

version: '3.8'

services:
  database:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - service
  backend:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - service
    depends_on:
      - database
networks:
  service: